### ISSUE TITLE
Text replace

### ISSUE THREAD

**Issue by rozxter1** [galkahana/HummusJS#454]
Is there any working example for text replacing with current Hummus version used ?

I have tried for text replace https://github.com/galkahana/HummusJS/issues/71#issuecomment-394203268 - is not working with current HummusJs version (1.0.110) .
Gives error :
```TypeError: pageObject.getDictionary(...).toJSObject(...).Contents.getObjectID is not a function```
Disabling that line, gives new error:
```
const readStream = copyingContext.getSourceDocumentParser().startReadingFromStream(textStream)
                                                                            ^
TypeError: Wrong arguments. provide a PDF stream input
```
All other examples around web whats based on that reply also is not working.
Maybe someone can say what version was used for that example?

Thank you!
